---
abstract: 'Delegate Extraction based on class.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092450'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-GIN-Extract-ClassMap
provides:
  Search::GIN::Extract::ClassMap:
    file: lib/Search/GIN/Extract/ClassMap.pm
    version: 0.01002312
  Search::GIN::Extract::ClassMap::Does:
    file: lib/Search/GIN/Extract/ClassMap/Does.pm
    version: 0.01002312
  Search::GIN::Extract::ClassMap::Isa:
    file: lib/Search/GIN/Extract/ClassMap/Isa.pm
    version: 0.01002312
  Search::GIN::Extract::ClassMap::Like:
    file: lib/Search/GIN/Extract/ClassMap/Like.pm
    version: 0.01002312
  Search::GIN::Extract::ClassMap::Role:
    file: lib/Search/GIN/Extract/ClassMap/Role.pm
    version: 0.01002312
  Search::GIN::Extract::ClassMap::Types:
    file: lib/Search/GIN/Extract/ClassMap/Types.pm
    version: 0.01002312
requires:
  Moose: 0.90
  MooseX::Types: 0.19
  MooseX::Types::Moose: 0.19
  Search::GIN: 0.03
  Test::More: 0.92
  aliased: 0.30
  namespace::autoclean: 0.08
resources:
  repository: http://github.com/kentfredric/Search-GIN-Extract-ClassMap/tree
version: 0.01002312
